### ISSUE TITLE
feat: Retrieve SAML user attributes, include in state, and provide to AWS SCIM

### ISSUE THREAD

**Issue by ghost** [slashdevops/idp-scim-sync#50]
**Is your feature request related to a problem? Please describe.**

Just wrapped up most of the setup - things are working well so far with the manual test... thank you!

Though - I just realized that the current implementation does *not* support SAML user attributes, and I was really hoping to take advantage of AWS's relatively new  (Nov 2020) attribute-based access control ABAC: https://aws.amazon.com/blogs/aws/new-attributes-based-access-control-with-aws-single-sign-on/

**Describe the solution you'd like**

Modify code to also retrieve any custom attributes that have been mapped in the Google Workspace SAML app, and include those in the state file and diff when determining what to send to the AWS SCIM endpoint. 

**Additional context**

**Creating custom attributes in the Workspace user settings:** https://admin.google.com/ac/customschema:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/98858833/156968990-2431389d-15d3-4d7f-b15a-ed52784ba310.png">

**Mapping custom attributes in the AWS SSO SAML app:** https://admin.google.com/ac/apps/saml/XXXXXXXX/attrmapping
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/98858833/156969056-7b403c26-969a-4362-a25f-1ea66365adc7.png">

**AWS SSO attribute-based access mappings**: https://us-west-2.console.aws.amazon.com/singlesignon/identity/home?region=us-west-2#!/settings?tab=abac
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/98858833/156969290-fa9d2b6f-503a-47c2-b416-9ee000d91806.png">

**Comment by christiangda** [comment]
Hi @mat-release totally agree with you, it could be a great feature.

I need to understand a little more how could be integration because actually I only use the [AWS SSO SCIM API](https://docs.aws.amazon.com/singlesignon/latest/developerguide/supported-apis.html) which is just used to populate `users, groups and groups members` with fixed fields or attributes I request to [Google Workspace Directory API](https://developers.google.com/admin-sdk/directory).

So, to do that I need to implement the [AWS SSO SDK go v2](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sso) or another `AWS SSO API` to retrieve the `SAML v1 mapping configuration`, but in my first research, I don't find any `AWS API` that allows us to retrieve this `SAML` information. I'll keep investigating how retrieving information is possible.

**Comment by christiangda** [comment]
Hi there,

Unfortunately, this is not possible, the SAML attributes are not reachable from the lambda and the Google credentials.  I implemented all the attributes allowed by the SCIM API, next version will allow you to have these.
